---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd.yaml
- nfs-subdir-external-provisioner.yaml
- sealed-secrets.yaml
- kubernetes-dashboard.yaml
- cloudflared.yaml
- wordpress.yaml
